// This file is auto-generated by @hey-api/openapi-ts

export type CreateTaskSchema = {
    title: string;
    description: string;
    priority?: 'low' | 'medium' | 'normal' | 'high';
    status?: 'pending' | 'in_progress' | 'completed';
    tag?: (string | null);
};

export type priority = 'low' | 'medium' | 'normal' | 'high';

export const priority = {
    LOW: 'low',
    MEDIUM: 'medium',
    NORMAL: 'normal',
    HIGH: 'high'
} as const;

export type status = 'pending' | 'in_progress' | 'completed';

export const status = {
    PENDING: 'pending',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed'
} as const;

export type TaskSchema = {
    id?: (number | null);
    title: string;
    priority?: string;
    description?: (string | null);
    completed?: boolean;
    created_at: string;
    status?: string;
    tag?: (string | null);
    deadline?: (string | null);
    ended_at?: (string | null);
    updated_at: string;
};

export type AppApiListTasksData = {
    title?: string;
};

export type AppApiListTasksResponse = (Array<TaskSchema>);

export type AppApiCreateTaskData = {
    requestBody: CreateTaskSchema;
};

export type AppApiCreateTaskResponse = (TaskSchema);

export type AppApiGetTaskData = {
    taskId: number;
};

export type AppApiGetTaskResponse = (TaskSchema);

export type AppApiUpdateTaskData = {
    requestBody: CreateTaskSchema;
    taskId: number;
};

export type AppApiUpdateTaskResponse = (CreateTaskSchema);

export type AppApiDeleteTaskData = {
    taskId: number;
};

export type AppApiDeleteTaskResponse = (void);