# Generated by Django 5.1.5 on 2025-02-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_session_user_verification_delete_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountId',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='providerId',
            new_name='provider_id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updateAt',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='expiresAt',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='updateAt',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emailVerified',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='expiredAt',
            new_name='expired_at',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='updateAt',
            new_name='update_at',
        ),
    ]
