# Generated by Django 5.1.5 on 2025-02-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_account_id_alter_session_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='verification',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
