# Generated by Django 5.1.5 on 2025-02-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_session_token_alter_verification_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='expires_at',
            new_name='expired_at',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
