# Generated by Django 5.1.5 on 2025-02-12 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='update_at',
        ),
        migrations.AddField(
            model_name='account',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='access_token_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='id_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='refresh_token_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='scope',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
