# Generated by Django 5.1.5 on 2025-02-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_account_update_at_account_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
